//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace authorization
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int id { get; set; }
        public string Article { get; set; }
        public string Name { get; set; }
        public string UnitOfMeasurement { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<double> MaximumPossibleDiscount { get; set; }
        public string Manufacturer { get; set; }
        public string Supplier { get; set; }
        public string Category { get; set; }
        public Nullable<double> CurrentDiscount { get; set; }
        public Nullable<double> QuantityInStock { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
    }
}
